version: '3.10'
services:
  web:
    container_name: app
    build: .
    command:  bash -c "python /usr/src/app/manage.py migrate --noinput &&
              python /usr/src/app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: